//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int fid { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public string cutype { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string addr { get; set; }
        public string phone { get; set; }
        public string post { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string link_man { get; set; }
        public string remark { get; set; }
        public string xtcu_no { get; set; }
        public string passwd { get; set; }
        public string unitcode { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string lc_no { get; set; }
        public string loca { get; set; }
        public string acting { get; set; }
        public string acting_cu_no { get; set; }
        public string imgurl { get; set; }
        public string type { get; set; }
        public string gclass { get; set; }
        public string xtName { get; set; }
        public string xtWxId { get; set; }
        public string myHead { get; set; }
        public string mySfz { get; set; }
        public string myPhoto { get; set; }
        public string WxId { get; set; }
        public string QQ { get; set; }
        public string WanWan { get; set; }
        public string checkyn { get; set; }
        public string item { get; set; }
        public Nullable<int> itlevel { get; set; }
        public string ht_no { get; set; }
        public string xtcheckyn { get; set; }
        public Nullable<int> cstatus { get; set; }
        public string fmoney { get; set; }
        public string taoid { get; set; }
        public string shitidian { get; set; }
        public string salloca { get; set; }
        public string zfb { get; set; }
        public string khh { get; set; }
        public string yhzh { get; set; }
        public Nullable<int> maxstorenum { get; set; }
    }
}
