//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhm_cust
    {
        public int fid { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public string remark { get; set; }
        public Nullable<int> codeLen { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string renote { get; set; }
        public string vyn { get; set; }
        public Nullable<int> vlen { get; set; }
        public string wlyn { get; set; }
        public Nullable<int> wlLen { get; set; }
        public string wlpr { get; set; }
        public string snyn { get; set; }
        public string snpr { get; set; }
    }
}
