//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhm_fwout
    {
        public int fid { get; set; }
        public string UnitCode { get; set; }
        public Nullable<decimal> SellCount { get; set; }
        public Nullable<decimal> myBegin { get; set; }
        public Nullable<System.DateTime> SellDateTime { get; set; }
        public string snbegin { get; set; }
        public string snend { get; set; }
        public Nullable<decimal> mqty { get; set; }
        public string packtype { get; set; }
        public Nullable<int> pdqty { get; set; }
        public Nullable<int> pzqty { get; set; }
        public Nullable<int> pxqty { get; set; }
        public Nullable<int> bxqty { get; set; }
        public Nullable<int> sxqty { get; set; }
        public string remark { get; set; }
        public string dxtyn { get; set; }
        public string dzfyn { get; set; }
        public string xnvyn { get; set; }
        public string fwpr { get; set; }
        public string wlpr { get; set; }
        public string snpr { get; set; }
        public string lfwyn { get; set; }
        public string lwlyn { get; set; }
        public string lsnyn { get; set; }
        public Nullable<int> codeLen { get; set; }
    }
}
