//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fw_cust
    {
        public int fid { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public string Addr { get; set; }
        public string Master { get; set; }
        public string Phone { get; set; }
        public string Post { get; set; }
        public string Fax { get; set; }
        public string Property { get; set; }
        public string remark { get; set; }
        public Nullable<int> codeLen { get; set; }
        public Nullable<int> Mlength { get; set; }
        public string MaxValue { get; set; }
        public System.DateTime RegDate { get; set; }
        public string Operator { get; set; }
        public Nullable<int> OverK { get; set; }
        public string VoiceWelcome { get; set; }
        public string smsnote { get; set; }
        public string bcode { get; set; }
        public string upyn { get; set; }
        public string voicere { get; set; }
        public string renote { get; set; }
        public Nullable<int> vlen { get; set; }
        public string jfyn { get; set; }
        public string zjyn { get; set; }
        public Nullable<decimal> aajf { get; set; }
        public string password { get; set; }
        public string p_no { get; set; }
        public string unitinfo { get; set; }
        public string prodinfo { get; set; }
        public byte[] zp { get; set; }
        public string ccodeyn { get; set; }
        public string ctype { get; set; }
        public string sntype { get; set; }
        public Nullable<int> snLen { get; set; }
        public Nullable<int> Msnlength { get; set; }
        public string dckyn { get; set; }
        public string snpr { get; set; }
        public string chrtype { get; set; }
    }
}
