//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gy_Czygl
    {
        public int fid { get; set; }
        public string czybm { get; set; }
        public string czymc { get; set; }
        public string czmm { get; set; }
        public string deptname { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string sysrole { get; set; }
        public Nullable<int> sysgroupid { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public string checkyn { get; set; }
        public string st_no { get; set; }
        public Nullable<System.DateTime> last_time { get; set; }
        public string last_ip { get; set; }
        public string unitcode { get; set; }
        public string remark { get; set; }
        public string rms_name { get; set; }
    }
}
