//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hob_setup
    {
        public int fid { get; set; }
        public string dian_no { get; set; }
        public string dian_name { get; set; }
        public string wishing { get; set; }
        public string act_name { get; set; }
        public string remark { get; set; }
        public string act_note { get; set; }
        public string unit_note { get; set; }
        public string hbnotes { get; set; }
        public string hbtop { get; set; }
        public string hbboot { get; set; }
        public string hbappID { get; set; }
        public Nullable<decimal> yuer { get; set; }
        public string yertype { get; set; }
        public string hbgettype { get; set; }
        public string csloca { get; set; }
        public string cszilao { get; set; }
        public string csguanzhu { get; set; }
        public string csship { get; set; }
        public string unitcode { get; set; }
        public Nullable<int> mutihb { get; set; }
        public Nullable<int> mutitime { get; set; }
        public Nullable<int> csshare { get; set; }
        public string shareurl { get; set; }
        public string shareimg { get; set; }
        public string sharetitle { get; set; }
        public string noactive { get; set; }
        public string nozj { get; set; }
    }
}
