//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hob_share
    {
        public int fid { get; set; }
        public string sharename { get; set; }
        public string sharenotes { get; set; }
        public string shareurl { get; set; }
        public string imgurl { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string dian_no { get; set; }
        public string unitcode { get; set; }
    }
}
