//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hob_listjuan
    {
        public int fid { get; set; }
        public string juan_no { get; set; }
        public string wx_id { get; set; }
        public string wx_name { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<int> Jp_id { get; set; }
        public string Jp_name { get; set; }
        public Nullable<decimal> jf { get; set; }
        public Nullable<int> status { get; set; }
        public string linkname { get; set; }
        public string linktell { get; set; }
        public string linkaddr { get; set; }
        public Nullable<int> tcode { get; set; }
        public string dian_no { get; set; }
        public string dian_name { get; set; }
        public string djtype { get; set; }
        public string djoper { get; set; }
        public Nullable<System.DateTime> Kin_date { get; set; }
        public string djremark { get; set; }
        public string fwcode { get; set; }
    }
}
