//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hob_yuerout
    {
        public int fid { get; set; }
        public string bill_no { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<decimal> mqty { get; set; }
        public string unitcode { get; set; }
        public string czybm { get; set; }
        public string remark { get; set; }
        public string wx_id { get; set; }
        public string wx_name { get; set; }
        public string outremark { get; set; }
        public string wxsex { get; set; }
        public string fwcode { get; set; }
        public string wlcode { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string loca { get; set; }
        public string address { get; set; }
        public string itme_no { get; set; }
        public string jp_name { get; set; }
        public Nullable<int> status { get; set; }
        public string keycode { get; set; }
        public string yertype { get; set; }
        public Nullable<int> tcode { get; set; }
        public string dian_no { get; set; }
        public string dian_name { get; set; }
    }
}
