//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hob_dzpsetup
    {
        public int fid { get; set; }
        public string dian_no { get; set; }
        public string act_note { get; set; }
        public string remark { get; set; }
        public string hbimg { get; set; }
        public Nullable<int> hbang { get; set; }
        public Nullable<int> mutihb { get; set; }
        public Nullable<int> mutitime { get; set; }
        public string shareurl { get; set; }
        public string sharetitle { get; set; }
        public string shareurlimg { get; set; }
    }
}
