//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hob_code
    {
        public int fid { get; set; }
        public string fwcode { get; set; }
        public string snno { get; set; }
        public string useyn { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public string remark { get; set; }
        public string cu_no { get; set; }
        public string dian_no { get; set; }
        public string hbitems { get; set; }
        public Nullable<int> tcode { get; set; }
    }
}
