//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hob_item
    {
        public int fid { get; set; }
        public string itme_no { get; set; }
        public string itme_name { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<System.DateTime> en_date { get; set; }
        public string itemtype { get; set; }
        public Nullable<decimal> mqtyf { get; set; }
        public Nullable<decimal> mqtyt { get; set; }
        public Nullable<decimal> hmlv { get; set; }
        public string unitcode { get; set; }
        public string remark { get; set; }
        public string actyn { get; set; }
        public Nullable<decimal> avqty { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public string jp_name { get; set; }
        public string jpnotes { get; set; }
        public string p_no { get; set; }
        public string pname { get; set; }
        public string dian_no { get; set; }
        public string bjlist { get; set; }
    }
}
