//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hob_bfwjf
    {
        public int fid { get; set; }
        public string snnof { get; set; }
        public string snnot { get; set; }
        public Nullable<int> snqty { get; set; }
        public string p_no { get; set; }
        public string pname { get; set; }
        public Nullable<decimal> jf { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string remark { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public string lot_no { get; set; }
        public string imgurl { get; set; }
        public Nullable<int> mqty { get; set; }
        public string revoc { get; set; }
        public Nullable<int> tcode { get; set; }
        public string hbitems { get; set; }
        public string xtcu_no { get; set; }
        public string xtcu_name { get; set; }
        public string unitcode { get; set; }
        public string dian_no { get; set; }
        public string salitems { get; set; }
    }
}
