//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hy_dian
    {
        public int fid { get; set; }
        public string hy_no { get; set; }
        public string hy_cn { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<decimal> jf { get; set; }
        public Nullable<decimal> historyjf { get; set; }
        public string realname { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public string BankAccount { get; set; }
        public string khh { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string loca { get; set; }
        public Nullable<int> statu { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string postcode { get; set; }
        public string address { get; set; }
        public string sex { get; set; }
        public string sfz_no { get; set; }
        public string imgurl { get; set; }
        public string Grade_no { get; set; }
        public string diagnosis_result { get; set; }
        public string post_adress { get; set; }
        public string unitcode { get; set; }
        public string xttype { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public string wx_id { get; set; }
        public string province { get; set; }
        public string city { get; set; }
    }
}
