//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStoreDetail
    {
        public int fid { get; set; }
        public string billno { get; set; }
        public Nullable<System.DateTime> indate { get; set; }
        public string p_no { get; set; }
        public string pname { get; set; }
        public string barcode { get; set; }
        public string ptype { get; set; }
        public string batchnum { get; set; }
        public Nullable<double> num { get; set; }
        public Nullable<decimal> inprice { get; set; }
        public Nullable<decimal> sumprice { get; set; }
        public string storenum { get; set; }
    }
}
