//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Mpart
    {
        public int fid { get; set; }
        public string p_no { get; set; }
        public string pname { get; set; }
        public string type { get; set; }
        public string unit { get; set; }
        public string loca { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<decimal> price { get; set; }
        public string parttype { get; set; }
        public Nullable<int> qcdays { get; set; }
        public Nullable<int> saftqty { get; set; }
        public string bm_no { get; set; }
        public Nullable<int> pqty { get; set; }
        public string usetype { get; set; }
        public string usefor { get; set; }
        public string imgurl { get; set; }
        public string unitcode { get; set; }
    }
}
