//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Stqty
    {
        public int fid { get; set; }
        public string p_no { get; set; }
        public string st_no { get; set; }
        public Nullable<decimal> stqty { get; set; }
        public Nullable<decimal> bakqty { get; set; }
        public Nullable<decimal> inqty { get; set; }
        public Nullable<decimal> outqty { get; set; }
        public Nullable<System.DateTime> m_date { get; set; }
        public string unitcode { get; set; }
        public Nullable<decimal> fgiqty { get; set; }
    }
}
