//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Store
    {
        public int fid { get; set; }
        public string st_no { get; set; }
        public string st_name { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string m_user { get; set; }
        public string sttype { get; set; }
        public string unitcode { get; set; }
        public string xtcu_no { get; set; }
    }
}
