//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_mlot
    {
        public int fid { get; set; }
        public string lot_no { get; set; }
        public string ship_no { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public Nullable<int> mqty { get; set; }
        public string p_no { get; set; }
        public string pname { get; set; }
        public string type { get; set; }
        public string unitcode { get; set; }
        public string mlot_no { get; set; }
        public string xtUserno { get; set; }
        public string remark { get; set; }
        public string pc_no { get; set; }
        public string pc_name { get; set; }
        public string op_no { get; set; }
        public string op_name { get; set; }
        public string msnno { get; set; }
        public Nullable<System.DateTime> eship_date { get; set; }
        public string imgurl { get; set; }
        public string mpart { get; set; }
        public string makeinfo { get; set; }
        public string reuser { get; set; }
        public string lop_no { get; set; }
        public string lop_name { get; set; }
        public string sop_no { get; set; }
        public string sop_name { get; set; }
        public string qc_no { get; set; }
    }
}
