//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Part
    {
        public int fid { get; set; }
        public string p_no { get; set; }
        public string pname { get; set; }
        public string type { get; set; }
        public string unit { get; set; }
        public string loca { get; set; }
        public string remark { get; set; }
        public string remark2 { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string m_user { get; set; }
        public Nullable<decimal> sfqty { get; set; }
        public Nullable<decimal> price { get; set; }
        public string cur_no { get; set; }
        public string mtype { get; set; }
        public Nullable<decimal> back { get; set; }
        public Nullable<decimal> stqty { get; set; }
        public Nullable<System.DateTime> st_date { get; set; }
        public Nullable<decimal> inqty { get; set; }
        public Nullable<decimal> outqty { get; set; }
        public string parttype { get; set; }
        public Nullable<decimal> curprice { get; set; }
        public Nullable<decimal> curchang { get; set; }
        public string prodtype { get; set; }
        public Nullable<int> qcdays { get; set; }
        public Nullable<int> saftqty { get; set; }
        public string bm_no { get; set; }
        public Nullable<int> pqty { get; set; }
        public Nullable<decimal> mprice { get; set; }
        public Nullable<decimal> mpack { get; set; }
        public Nullable<decimal> mall { get; set; }
        public string fwcode { get; set; }
        public string usetype { get; set; }
        public string usefor { get; set; }
        public string xtcu_no { get; set; }
        public Nullable<decimal> jf { get; set; }
        public Nullable<decimal> ajf { get; set; }
        public Nullable<decimal> bjf { get; set; }
        public Nullable<decimal> cjf { get; set; }
        public string upyn { get; set; }
        public Nullable<int> zqty { get; set; }
        public string unitcode { get; set; }
        public string imgurl { get; set; }
        public string imgurl2 { get; set; }
        public string imgurl3 { get; set; }
        public string imgurl4 { get; set; }
        public string pnamejs { get; set; }
        public string fwnote { get; set; }
        public string renote { get; set; }
        public Nullable<int> p_star { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public Nullable<int> oid { get; set; }
        public string hbitems { get; set; }
        public string salitems { get; set; }
    }
}
