//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdauser
    {
        public int fid { get; set; }
        public string pdano { get; set; }
        public string pdaname { get; set; }
        public string pdapwd { get; set; }
        public string cu_no { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public string phone { get; set; }
        public string realname { get; set; }
    }
}
