//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_tiaoji
    {
        public int fid { get; set; }
        public string ship_no { get; set; }
        public string bsnno { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public string checkyn { get; set; }
        public string oclass { get; set; }
        public string nclass { get; set; }
    }
}
