//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_tst
    {
        public int fid { get; set; }
        public string ship_no { get; set; }
        public string bsnno { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public Nullable<int> mqty { get; set; }
        public string p_no { get; set; }
        public string pname { get; set; }
        public string type { get; set; }
        public string ost_no { get; set; }
        public string nst_no { get; set; }
        public string remark { get; set; }
        public string unitcode { get; set; }
    }
}
