//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_ship
    {
        public int fid { get; set; }
        public string ship_no { get; set; }
        public string bsnno { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public string loca { get; set; }
        public Nullable<int> mqty { get; set; }
        public string p_no { get; set; }
        public string pname { get; set; }
        public string upyn { get; set; }
        public string xtcu_no { get; set; }
        public Nullable<decimal> jf { get; set; }
        public Nullable<decimal> price { get; set; }
        public string type { get; set; }
        public string unitcode { get; set; }
        public string lot_no { get; set; }
        public string st_no { get; set; }
        public string xtcu_name { get; set; }
        public string cureyn { get; set; }
        public Nullable<System.DateTime> curedate { get; set; }
        public string bloca { get; set; }
        public string cloca { get; set; }
        public string mtype { get; set; }
        public string po_no { get; set; }
        public string recu_no { get; set; }
        public string recu_name { get; set; }
        public string renotes { get; set; }
        public string pda_no { get; set; }
        public string reship_no { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> adddatetime { get; set; }
    }
}
