//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_packa
    {
        public int fid { get; set; }
        public string pack_no { get; set; }
        public Nullable<System.DateTime> pack_date { get; set; }
        public string pfilename { get; set; }
        public string uplog { get; set; }
        public string unitcode { get; set; }
        public string line_no { get; set; }
        public string wo_no { get; set; }
        public string log_no { get; set; }
        public string p_no { get; set; }
        public string remark { get; set; }
        public string absolutepath { get; set; }
        public string relativepath { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public string type { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> okqty { get; set; }
        public Nullable<int> errqty { get; set; }
        public Nullable<int> okpcs { get; set; }
        public string cu_no { get; set; }
    }
}
