//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vender
    {
        public int fid { get; set; }
        public string cu_no { get; set; }
        public string cu_name { get; set; }
        public string cutype { get; set; }
        public string lc_no { get; set; }
        public string loca { get; set; }
        public string addr { get; set; }
        public string phone { get; set; }
        public string post { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string link_man { get; set; }
        public string remark { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string acting { get; set; }
        public string acting_cu_no { get; set; }
        public string xtcu_no { get; set; }
        public string passwd { get; set; }
        public string unitcode { get; set; }
        public string zizhi { get; set; }
    }
}
