//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_gid
    {
        public int fid { get; set; }
        public string unitcode { get; set; }
        public string unitname { get; set; }
        public string WxId { get; set; }
        public string WxNo { get; set; }
        public string WxName { get; set; }
        public string AppId { get; set; }
        public string AppSecret { get; set; }
        public string WxUrl { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string remark { get; set; }
        public string mchid { get; set; }
        public string mkey { get; set; }
        public string msslpath { get; set; }
        public string msslpasswd { get; set; }
    }
}
