//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_mnu
    {
        public int fid { get; set; }
        public string unitcode { get; set; }
        public string unitname { get; set; }
        public string mnuitem { get; set; }
        public string mnuname { get; set; }
        public string keyname { get; set; }
        public string shouyn { get; set; }
        public string mnuurl { get; set; }
        public string mnuidex { get; set; }
        public string pmnuname { get; set; }
        public string remark { get; set; }
        public string wxtype { get; set; }
        public string wxnote { get; set; }
        public Nullable<int> appid_boot { get; set; }
    }
}
