//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xt_images
    {
        public int fid { get; set; }
        public string img_name { get; set; }
        public string imgtype { get; set; }
        public string tempimage { get; set; }
        public string unitcode { get; set; }
        public string remark { get; set; }
        public string sindex { get; set; }
        public string reurl { get; set; }
    }
}
