//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xt_shebei
    {
        public int fid { get; set; }
        public string op_no { get; set; }
        public string op_name { get; set; }
        public string remark { get; set; }
        public string unitcode { get; set; }
        public string job { get; set; }
        public string jkzk { get; set; }
        public string peixun { get; set; }
        public string lzqk { get; set; }
        public string qkjs { get; set; }
        public string xdlist { get; set; }
    }
}
