//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xt_uplist
    {
        public int fid { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string filename { get; set; }
        public Nullable<int> mqty { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> up_date { get; set; }
        public Nullable<int> status { get; set; }
    }
}
