//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xt_unit
    {
        public int fid { get; set; }
        public string unitcode { get; set; }
        public string unitname { get; set; }
        public string cutype { get; set; }
        public string addr { get; set; }
        public string phone { get; set; }
        public string post { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string link_man { get; set; }
        public string remark { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string acting { get; set; }
        public string passwd { get; set; }
        public Nullable<int> sninyn { get; set; }
        public Nullable<int> packtype { get; set; }
        public string logo { get; set; }
        public string fwunitcode { get; set; }
        public string fwyn { get; set; }
        public string jfyn { get; set; }
        public string fcyn { get; set; }
        public string fgiyn { get; set; }
        public string prdyn { get; set; }
        public string recl { get; set; }
        public string qcyn { get; set; }
        public string styn { get; set; }
        public string ckyn { get; set; }
        public string fcnote { get; set; }
        public string thcl { get; set; }
        public string hyzl { get; set; }
        public string hbyn { get; set; }
        public string wishing { get; set; }
        public string act_name { get; set; }
        public string act_note { get; set; }
        public string unit_note { get; set; }
        public string nyyn { get; set; }
        public string weburl { get; set; }
        public string qc01 { get; set; }
        public string qc02 { get; set; }
        public string qc03 { get; set; }
        public string futyn { get; set; }
        public string zbyn { get; set; }
    }
}
