//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmbzbfwfc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xt_xtmenu
    {
        public int fid { get; set; }
        public string gnbm { get; set; }
        public string gnsy { get; set; }
        public string gnmc { get; set; }
        public string sjgnbm { get; set; }
        public Nullable<int> mjbz { get; set; }
        public Nullable<int> MenuList { get; set; }
        public Nullable<int> RightFlag { get; set; }
        public string acturl { get; set; }
        public string icostyle { get; set; }
        public string rightlist { get; set; }
        public string remark { get; set; }
    }
}
